spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car
    username: root
    password: root
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'health, prometheus'